### ISSUE TITLE
No Module named Jetson

### ISSUE THREAD

**Issue by BaconIsAVeg** [yskoht/raspberry-epaper#2]
```
(.venv) atlas@pi4:~ $ epaper print --device="epd2in7b_V2" display.txt
2024-01-21 22:35:55,981 [INFO](filepath.py:94:get_filepath_and_mimetype) File path:display.txt
2024-01-21 22:35:55,981 [INFO](filepath.py:97:get_filepath_and_mimetype) Mimetype:text/plain
2024-01-21 22:35:55,991 [ERROR](print.py:71:process) No module named 'Jetson'
2024-01-21 22:35:55,994 [ERROR](print.py:72:process) Traceback (most recent call last):
  File "/home/atlas/.venv/lib/python3.11/site-packages/raspberry_epaper/print.py", line 50, in process
    epd = EPD(arg.device.value)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/.venv/lib/python3.11/site-packages/raspberry_epaper/epd.py", line 14, in __init__
    self.epdLib = epaper.epaper(device)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/.venv/lib/python3.11/site-packages/epaper/__init__.py", line 12, in epaper
    return importlib.import_module('{}.{}'.format(path, model))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/atlas/.venv/lib/python3.11/site-packages/epaper/e-Paper/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd2in7b_V2.py", line 32, in <module>
    from . import epdconfig
  File "/home/atlas/.venv/lib/python3.11/site-packages/epaper/e-Paper/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epdconfig.py", line 222, in <module>
    implementation = JetsonNano()
                     ^^^^^^^^^^^^
  File "/home/atlas/.venv/lib/python3.11/site-packages/epaper/e-Paper/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epdconfig.py", line 115, in __init__
    import Jetson.GPIO
ModuleNotFoundError: No module named 'Jetson'
```

Linux pi4 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

**Comment by BaconIsAVeg** [comment]
The example code from the waveshare e-paper repo worked fine however.
